version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: selenium-tests
    volumes:
      - .:/app
    ports:
      - "8000:8000"